version: '3.6'
services:

  postgres:
    image: postgres
    volumes:
    - bareksa_project_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    ports:
      - "7777:5432"
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend
    ports:
    - "${BACKEND_PORT:?err}:8888"
    depends_on:
    - "postgres"
    restart: always

volumes:
  bareksa_project_db:
